controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    diff_controller_alphabot2:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_controller_alphabot2:
  ros__parameters:
    update_rate: 50  # Hz

    base_frame_id: telo

    left_wheel_names: ["lave_koleso_zaves"]
    right_wheel_names: ["prave_koleso_zaves"]
    wheel_separation: 0.088
    wheel_radius: 0.022

    use_stamped_vel: false

    position_feedback: false
    open_loop: true
    enable_odom_tf: true

    linear.x.max_velocity: 0.16
    linear.x.min_velocity: -0.16
    linear.x.max_acceleration: .NAN
    linear.x.max_deceleration: .NAN
    linear.x.max_acceleration_reverse: .NAN
    linear.x.max_deceleration_reverse: .NAN
    linear.x.max_jerk: .NAN
    linear.x.min_jerk: .NAN

    angular.z.max_velocity: 2.09
    angular.z.min_velocity: -2.09
    angular.z.max_acceleration: .NAN
    angular.z.max_deceleration: .NAN
    angular.z.max_acceleration_reverse: .NAN
    angular.z.max_deceleration_reverse: .NAN
    angular.z.max_jerk: .NAN
    angular.z.min_jerk: .NAN

# joint_state_broadcaster:
#   ros__parameters:
