teleop_twist_joy_node:
  ros__parameters:
    publish_stamped_twist: true
    require_enable_button: false
    axis_linear:
      x: 1            # Left stick Up/Down (index to axes of /joy topic)
    axis_angular:
      yaw: 0          # Left stick Left/Right (index to axes of /joy topic)
    scale_linear:
      x: 0.2          # Max speed in m/s (max_vel_x in nav2)
    scale_angular:
      yaw: 0.6        # Max turn speed in rad/s (max_vel_theta in nav2)
