amcl:
  ros__parameters:
    use_sim_time: False
    base_frame_id: "telo"
    odom_frame_id: "odom"
    scan_topic: "scan"
    transform_tolerance: 0.5

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      robot_base_frame: "telo"
      global_frame: "map"
      robot_radius: 0.06
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.08          # stay 10 cm away from walls (center of robot?)
        cost_scaling_factor: 10.0

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      robot_base_frame: "telo"
      global_frame: "odom"
      robot_radius: 0.06
      rolling_window: True
      width: 3
      height: 3
      resolution: 0.02
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.08          # stay 10 cm away from walls (center of robot?)
        cost_scaling_factor: 10.0

bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: "map"
    robot_base_frame: "telo"
    odom_topic: "odom"
    default_nav_to_pose_bt_xml: "/opt/ros/kilted/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml"

controller_server:
  ros__parameters:
    use_sim_time: False
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: True
      # Alphabot2 is small; keep these limits low
      min_vel_x: 0.01
      max_vel_x: 0.2
      min_vel_y: 0.0
      max_vel_y: 0.0
      min_speed_xy: 0.05
      max_speed_xy: 0.85
      min_speed_theta: 0.4
      max_vel_theta: 2.0
      acc_lim_x: 0.3
      acc_lim_theta: 1.0
      vx_samples: 30       # Increase from default
      vy_samples: 1       # Must be 1 for differential drive (no lateral movement)
      vtheta_samples: 50   # Increase from default
      sim_time: 1.5        # Shorter simulation time for tight spaces
      #sim_granularity: 0.025
      #use_grid_path: true
      # critics
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      BaseObstacle.scale: 0.02
      PathAlign.scale: 32.0
      PathAlign.forward_point_distance: 0.1
      GoalAlign.scale: 24.0
      GoalAlign.forward_point_distance: 0.1
      PathDist.scale: 32.0
      GoalDist.scale: 24.0
      RotateToGoal.scale: 32.0
      RotateToGoal.slowing_factor: 5.0
      RotateToGoal.lookahead_time: -1.0

      #oscillation_reset_dist: 0.12   # Distance in meters (increase from default 0.05)
      #oscillation_reset_angle: 0.4   # Angle in radians (increase from default 0.2)
      #oscillation_reset_time: 1.5    # Seconds to wait before panicking

planner_server:
  ros__parameters:
    use_sim_time: False
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner::NavfnPlanner"

behavior_server:
  ros__parameters:
    use_sim_time: False
    global_frame: map
    local_frame: odom
    robot_base_frame: telo
    transform_tolerance: 0.5

